### PR TITLE
Fix: url hash not preserved after page reload

### LINKED ISSUE #104: Do not omit hash on initial page load when using History API
Hello! With the browser plugin enabled, and when it's `useHash` option is set to `false` IMO router should not omit the hash part of the url on initial page load. Now it is impossible to reload a page with the hash in the url - hash gets removed on reload.

It happens here, I believe - https://github.com/router5/router5/blob/master/modules/plugins/browser/browser.js#L31
Thanks!

### PR DESCRIPTION
**Pull request by iotch**
Fixes #104

### CODE REVIEW

**Comment by troch** [comment]
Thanks! Should `browser.getHash()` only be added when starting (transitioning to the first step)? If you load a new page `/route1#part-1`, and then navigate to `/route2`, the browser's URL would change to `/router2#part-1` rather than `/route2`?

**Comment by iotch** [comment]
Is it enough to check if `fromState` is null? Or I missed your point?

**Comment by iotch** [comment]
@troch, could you merge, please?

**Comment by troch** [comment]
Yep, sorry for the delay. Like #143, can you put this behaviour behind an option? Name it `preserveHash`, default to `false` for now, so current usage is not impacted. Reason for this is I'm not ready to bump a major version now (I'm in the process of refactoring the repo to host all packages, so major version bumps are made easier).

**Comment by troch** [comment]
Thanks!

**Pull request merged**
