### PR TITLE
Prettier tweaks

### PR DESCRIPTION
**Pull request by faergeek**
See #221

### CODE REVIEW

**Comment by faergeek** [comment]
Right now I have no idea why it fails on CI, but works locally. @troch Can you check if it works locally for you? May be I'm doing something wrong?

**Comment by faergeek** [comment]
Sorry, now I get it. It's because I didn't run `yarn run build` before `yarn run check` locally.

**Comment by faergeek** [comment]
Probably need to tweak `.prettierignore`. Not sure exactly which files are actually build artifacts. I just added to it everything on what prettier complained after `yarn run build` and `yarn run check`.

**Comment by faergeek** [comment]
@troch can you review these changes?

**Comment by troch** [comment]
Looks good. Can you drop semi colons? The project didn't have them initially but I struggled not using them while I was using them at work. But I now don't use them at work.

**Comment by faergeek** [comment]
@troch ESLint complained about semicolons, so I just added automatic checking for conflicting rules and removed them

**Pull request merged**
