### PR TITLE
Fix issue with browsers that don't URL encode characters (MS Edge, IE11)

### PR DESCRIPTION
**Pull request by todorpr**
Normally if we have in the URL non-latin characters (like Cyrillic, Greek), Chrome and Firefox (exception is the pipe `|` char here) browsers encode these characters. 

Example:
If we have URL with path `/абв` (in Cyrillic) and log `
window.location.pathname`, the result would be `/%D0%B0%D0%B1%D0%B2` in Chrome and Firefox

In Microsoft Edge and IE11 however, it's logged `/абв`, which leads  `@@router5/UNKNOWN_ROUTE`

What's the impact of the above issue:
`router5` doesn't work properly when URL contains such characters. That's why we need to always make sure the URL is encoded.

### CODE REVIEW

**Comment by troch** [comment]
Hi @todorpr, thanks for this. I'm going to test it out, I want to make sure the pipe issue is not going to re-appear.

**Comment by troch** [comment]
@todorpr could you update your PR? I've merged another PR for v7, and files have changed.

**Comment by todorpr** [comment]
@troch I updated the PR, sorry for the delay!

The `safelyEncodePath` is in case there is [Malformed URI](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Errors/Malformed_URI) leading to a [URIError](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/URIError)

For example `decodeURI("some-%-path")` or `decodeURI("some-%2-path")` would lead to `Uncaught URIError: URI malformed`. The only solution to this problem is a `try/catch` block.

**Comment by klimashkin** [comment]
Hi @todorpr!
Seems like this change breaks encoding in chrome in case of `useHash: true`.

Let's say I navigate with `params: {filter: JSON.srtringify({name: 'test'})}`,
and final path is `/#/table?filter={name: 'test'}` 
which gets decoded in url into `/#/table?filter=%7B"name"%3A"test"%7D`

Then, if I press refresh in browser, you code `encodeURI(decodeURI(path))` 
will convert it to `/#/table?filter=%7B%22name%22%253A%22test%22%7D` 
because decodeURI returns `/#/table?filter={"name"%3A"test"}` in this case 
(while `decodeURIComponent` would decode it correctly)

Seems like it's related to #404
Any thoughts on this?

**Comment by todorpr** [comment]
@klimashkin honestly this fix was only intended for `window.location.pathname` and I never tested it with hash, so maybe we need to isolate the `safelyEncodePath(path)` only when  `useHash: false`.

**Comment by troch** [comment]
@todorpr would you be able to make a PR 🙂 ?

**Comment by todorpr** [comment]
I will @troch ;)

**Comment by brotheroftux** [comment]
@troch @todorpr This fix breaks a case where encoded symbols like `&` are used in the path after browser refresh.

Observe:
1. Let's say user refreshes a page while being on a `/some/route/param%26` path.
2. `decodeURI('/some/route/param%26')` results in `/some/route/param%26`, `&` is not unescaped and remains in percent-encoded form
3. `encodeURI('/some/route/param%26')` results in `/some/route/param%2526`.
4. `decodeURIComponent('param%2526')` (troch/path-parser's default mode) results in `param%26`, so we get this value for the route path parameter instead of the expected `param&`.

I will work on an ad-hoc fix for our team's project, since we have a lot of path parameters with these special symbols that get affected by `encode/decodeURIComponent` but are ignored by `encode/decodeURI`. However, I do believe this is a bug.

**Comment by stellarhoof** [comment]
For posterity's sake, the easiest fix is to simply do `return new URL(path).toString()` [here](https://github.com/router5/router5/blob/master/packages/router5-plugin-browser/modules/browser.ts#L51)

**Pull request merged**
