### PR TITLE
Add listeners plugin methods to Router

### PR DESCRIPTION
**Pull request by jraoult**
The typescript definitions are lacking these extensions of Router when importing the listeners plugin. I've been using this custom definition for a while but I realised it might be helpful for someone else.

Hope you find them adequate @troch. Thanks for maintaining this repo by the way :)

### CODE REVIEW

**Comment by troch** [comment]
Hey thanks @jraoult, I'm going to try it out

**Comment by jraoult** [comment]
@troch have you had a chance to look at it?

**Comment by troch** [comment]
I did, and forgot to reply... The issue is that it adds the type definition to each router, irrespective of the listeners plugin being used.

What do you use the listeners plugin for?

**Comment by troch** [comment]
In that case you don't need the listeners plugin, you can simply use `subscribe` which has been added (6.1.0 I believe). It's incorrectly typed (see #288) but it takes a callback and returns an unsubscribe handler.

**Comment by jraoult** [comment]
@troch thanks for the hint. I guess if the idea is to deprecate the listener plugin this PR is now obsolete.

**Comment by troch** [comment]
The intention is not to deprecate it, but it is no longer needed for React or simple cases which only need to listen to route state changes.

**Pull request closed without merging**
