### PR TITLE
Add "jsnext:main" to the package.json to support Rollup

### PR DESCRIPTION
**Pull request by JonathanWolfe**
Adds support for Rollup - https://github.com/rollup/rollup/wiki/jsnext:main

### CODE REVIEW

**Comment by troch** [comment]
:+1: thanks. I have also added it to router5 dependencies: route-node and path-parser.

**Comment by JonathanWolfe** [comment]
Awesome. Let me know when you publish all those to npm.

**Comment by troch** [comment]
It's all published already!

**Comment by JonathanWolfe** [comment]
:+1:

**Pull request merged**
