### PR TITLE
Fix redux plugin type definition

### LINKED ISSUE #300: reduxPlugin typing is broken
Hey! I just noticed an issue in the typing of redux-router5 (redux-router5 v6.0.0, react-router5 v6.0.1, router5 v6.2.2).

```
./node_modules/redux-router5/index.d.ts
(17,28): Type 'TState' does not satisfy the constraint 'Action<any>'.
  Type '{ router: RouterState; }' is not assignable to type 'Action<any>'.
    Property 'type' is missing in type '{ router: RouterState; }'.
```

The issue appears to be in the reduxPlugin function type. When you are typing the `dispatch` argument, I believe it expects an object with a `type` field. But the current typing doesn't include a `type` field. I deleted this function definition locally and my build completed.

### PR DESCRIPTION
**Pull request by eatonphil**
Closes #300.

Does this make sense?

### CODE REVIEW

**Comment by troch** [comment]
The initial type signature is incorrect, `{ router: RouterState }` is the type of the reducer output rather than the type of actions dispatched.

Would you mind correcting it as well as adding `type`?

**Comment by eatonphil** [comment]
Got it. Look better now?

**Comment by troch** [comment]
`RouterState` is not exactly `payload`. I think `payload` should be:

```js
interface Action {
    type: string,
    payload?: {
        route: State
        previousRoute: State | null
        transitionError?: any
    }
}
```

**Comment by eatonphil** [comment]
Oh I see. How about now?

**Comment by troch** [comment]
Thanks 👍

**Pull request merged**
