### PR TITLE
Typescript typings specify routerNode instead of routeNode #230

### PR DESCRIPTION
**Pull request by texttechne**
fixed the typo.

### CODE REVIEW

**Comment by troch** [comment]
@texttechne thanks for the PR. Travis is reporting a failing test on type definitions, can you take a look?

**Comment by texttechne** [comment]
sure.

**Comment by texttechne** [comment]
The tests run fine locally. Currently there's a timeout:
```
Error: Timeout of 2000ms exceeded. For async tests and hooks, ensure "done()" is called; if returning a Promise, ensure it resolves.
```

**Comment by troch** [comment]
Yep, it seems to timeout on a regular basis...

**Comment by troch** [comment]
Released (react-router5@5.4.1), thanks 👍

**Comment by texttechne** [comment]
wow, what a quick response!

and thanks for this awesome library!

**Pull request merged**
