### PR TITLE
Fix README.md use of routeNodeSelector

### PR DESCRIPTION
**Pull request by eatonphil**
Was super confused checking my broken code against the docs for a while and was confused why you'd accept the state variable and not use it. This corrects the example to actually work and makes a little more sense too. :)

### CODE REVIEW

**Comment by zaeleus** [comment]
The example, though indeed redundant, is correct. `routeNodeSelector` will return a function, and redux will pass `state` to it whenever the store updates. If you execute the function beforehand, as in your patch, you return an object, making the wrapper function the selector. This means you reinitialize `routeNodeSelector` every call, which keeps track of the current and previous routes.

If you don't read `state`, you can simply subscribe to the store with `routeNodeSelector` directly.

```js
export default connect(routeNodeSelector(''))(Root);
```

**Comment by eatonphil** [comment]
I tried that first and oddly it didn't work. I do not know why.

**Comment by eatonphil** [comment]
Actually... I'm not sure I understand what you're saying. You're saying the example is is is correct? routeNodeSelector returns a function that expects `state` https://github.com/router5/router5/blob/master/packages/redux-router5/modules/lib/routeNodeSelector.js#L8. The example currently takes the state and ignores it, the interior routeNodeSelector function is not even called at all so nothing happens. I did try `connect(routeNodeSelector('')(Root))` and while I'd expect that to work because it appears to be the same as `state => routeNodeSelector('')(state)`, it did not.

**Comment by zaeleus** [comment]
Yes, the example does work as is. You're passing a function as the selector, not an object. When the store updates, redux is the one that calls it and passes the state as the argument. See the [docs for `connect`](https://github.com/reactjs/react-redux/blob/master/docs/api.md#connectmapstatetoprops-mapdispatchtoprops-mergeprops-options).

Note that `Root` is the component you want to wrap, not pass as the state, i.e.,

```diff
-connect(routeNodeSelector('')(Root))
+connect(routeNodeSelector(''))(Root)
```

**Comment by eatonphil** [comment]
I made a typo in that last comment, I meant `connect(routeNodeSelector(''))(Root)` like you wrote. It still does not cause the Root element's props to change when the route changes. So far, none of the suggestions have worked for me except the one I posted initially. The only reason it is different, as you pointed out is that the routeNodeSelector function gets called each time the state changes. For whatever reason, this is the only configuration that works for me. But I'll close this out if I'm the only only one for whom this works. (My only other thought is that this might have to do with me not having thunks set up in Redux?)

**Comment by zaeleus** [comment]
Here is a minimal working example. Maybe you can find the difference in your code?

https://gist.github.com/zaeleus/aab7b52c8fef3121d223dc89916eac8f

```
$ create-react-app redux-router5-test
$ cd redux-router5-test
$ yarn add react-redux react-router5 redux redux-router5 router5
$ curl https://gist.githubusercontent.com/zaeleus/aab7b52c8fef3121d223dc89916eac8f/raw/db36ae5b293c5bf9589f9d8467f3ab8e9ea8fdcf/index.js > src/index.js
$ yarn start
```

**Pull request closed without merging**
